"""initial_migration

Revision ID: 38cedd8015f9
Revises: 
Create Date: 2026-08-05 07:05:09.910239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38cedd8015f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email address (used for login)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="User's full name"),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='Bcrypt-hashed password (nullable for OAuth users)'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='Optional profile picture URL'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Account status flag'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Soft delete flag'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name of the project'),
    sa.Column('key', sa.String(length=10), nullable=False, comment='Unique project key for quick reference (e.g., PROJ-001)'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='Optional project description'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='ID of the user who owns the project'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Soft delete flag'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_projects_key'), 'projects', ['key'], unique=True)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='ID of the project'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the user'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='User role: Owner, Admin, Member, or Viewer'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Soft delete flag (allows reactivation)'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='unique_project_member')
    )
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_index(op.f('ix_project_members_is_deleted'), 'project_members', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Task title'),
    sa.Column('description', sa.String(length=2000), nullable=True, comment='Optional detailed description'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Current status: ToDo, InProgress, or Done'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='Task priority: Low, Medium, or High'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='ID of the parent project'),
    sa.Column('assignee_id', sa.Integer(), nullable=True, comment='ID of the user assigned to the task'),
    sa.Column('reporter_id', sa.Integer(), nullable=False, comment='ID of the user who created the task'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='Optional due date'),
    sa.Column('estimated_hours', sa.Integer(), nullable=True, comment='Estimated hours to complete the task'),
    sa.Column('logged_hours', sa.Integer(), nullable=True, comment='Actual hours logged (sum of timesheet entries)'),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True, comment='Flag for deadline reminder sent'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Soft delete flag'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_is_deleted'), 'tasks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_reporter_id'), 'tasks', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('activities',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the user who performed the action'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='ID of the project context'),
    sa.Column('task_id', sa.Integer(), nullable=True, comment='ID of the task (if action relates to a task)'),
    sa.Column('action', sa.String(length=500), nullable=False, comment='Human-readable action description'),
    sa.Column('details', sa.JSON(), nullable=True, comment='Additional context/data as JSON'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_project_id'), 'activities', ['project_id'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('content', sa.Text(), nullable=False, comment='The comment text content'),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='ID of the task this comment belongs to'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='ID of the user who wrote the comment'),
    sa.Column('mentions', sa.JSON(), nullable=True, comment='JSON array of user IDs mentioned in the comment'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Soft delete flag'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_is_deleted'), 'comments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.create_table('invitations',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address of the invited user'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='ID of the project being invited to'),
    sa.Column('task_id', sa.Integer(), nullable=True, comment='Optional task ID for task-specific invitations'),
    sa.Column('token', sa.String(length=100), nullable=False, comment='Unique UUID token for secure acceptance'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Current status: Pending, Accepted, or Expired'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Expiration timestamp (7 days from creation)'),
    sa.Column('inviter_id', sa.Integer(), nullable=True, comment='ID of the user who sent the invitation'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_invitations_project_id'), 'invitations', ['project_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the user receiving the notification'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Notification type: TaskAssigned, StatusChanged, etc.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short notification title'),
    sa.Column('content', sa.String(length=1000), nullable=False, comment='Detailed notification message'),
    sa.Column('task_id', sa.Integer(), nullable=True, comment='Optional related task ID'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='Optional related project ID'),
    sa.Column('action_url', sa.String(length=500), nullable=True, comment='URL to navigate when notification is clicked'),
    sa.Column('read', sa.Boolean(), nullable=True, comment='Read/unread status flag'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='Additional context data as JSON'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('task_collaborators',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='ID of the task'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the collaborator user'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id'),
    comment='Many-to-many relationship between tasks and collaborator users'
    )
    op.create_table('task_watchers',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='ID of the task'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the watcher user'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id'),
    comment='Many-to-many relationship between tasks and watcher users'
    )
    op.create_table('timesheets',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='ID of the task work was performed on'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the user who logged the time'),
    sa.Column('date', sa.Date(), nullable=False, comment='Date the work was performed'),
    sa.Column('hours', sa.Float(), nullable=False, comment='Number of hours worked'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the work done'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheets_id'), 'timesheets', ['id'], unique=False)
    op.create_index(op.f('ix_timesheets_task_id'), 'timesheets', ['task_id'], unique=False)
    op.create_index(op.f('ix_timesheets_user_id'), 'timesheets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheets_user_id'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_task_id'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_id'), table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_table('task_watchers')
    op.drop_table('task_collaborators')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_invitations_project_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_deleted'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_project_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_reporter_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_deleted'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_is_deleted'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_key'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
